### ISSUE TITLE
npm issue when running install

### ISSUE THREAD

**Issue by teshiburu** [samcm/PlexTogether#16]
I have an issue when running the npm install commands for either the client or server.

[npm-debug.txt](https://github.com/samcm/PlexTogether/files/704578/npm-debug.txt)
[npm-debug-client.txt](https://github.com/samcm/PlexTogether/files/704579/npm-debug-client.txt)

**Comment by samcm** [comment]
Have you got any anti-virus/malware software running? @teshiburu

**Comment by Kavex** [comment]
**Client for windows** 
1.  Download current nodejs https://nodejs.org/en/ 
2.  Downloads files from git
3. Run `npm install` within the root folder (PlexTogether-master)

Should work, if any issues try running `npm install -g electron`

**Comment by samcm** [comment]
As the electron app is now discontinued i'm going to close this
