### ISSUE TITLE
Error connecting to client - Cross-Origin Request Blocked: CORS preflight channel did not succeed

### ISSUE THREAD

**Issue by edgar-sanchez-is** [samcm/PlexTogether#19]
I'm getting an the following error message in PlexTogether:

> Error connecting to client

I'm also getting the following error in the browser console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://local_ip:port/player/timeline/poll?wait=0&commandID=0&type=video. (Reason: CORS preflight channel did not succeed).

See the screenshots:

![Browser Error](http://i.imgur.com/E6gUjhH.png)

![Console Output](http://i.imgur.com/HC7dZqz.png)

Is this a known issue or is there something I'm doing wrong? This is my setup:

* **Plex app on Apple TV 4th gen** (local)
* **Plex Media Server on Mac v1.5.3.3580** (local)
* **PlexTogether running on browser on Mac** (local)

I've tested with Safari, Firefox, and with Chrome, I get the same error message in all browsers. I can successfully ping my Apple TV from my computer. The Plex app is open on the Apple TV and it's connected to my local PMS.

**Comment by samcm** [comment]
Just looking at this again now. Thanks for the detailed summary. 

A 500 error from the ATV client most likely means the requests to the client are wrong/malformed. I did have AppleTV working at one stage but something may have broken it - it seems to be one of the more picky clients with regards to having every request perfect. I will probably have some time later on in the week to sit down and do some testing after Uni has died down.

**Comment by samcm** [comment]
Closing this for now as there is more information in #26
