### ISSUE TITLE
Issues when running server

### ISSUE THREAD

**Issue by ofurpesi** [samcm/PlexTogether#21]
Hi there :)

After i run the last command "node server.js" and i try to access the website on port 8089, i get this on the website:

Cannot Get /

Any ideas?

**Comment by samcm** [comment]
Hey mate.

The server software isn't meant to be accessed directly, you're meant to connect to it via the web app. For details on how to set up the web app have a look here:
https://github.com/samcm/PlexTogether#building-the-app

Alternatively you can use the live version we run at http://app.plextogether.com

I should probably add a short message to the server software that clarifies this if its accessed directly.

**Comment by ofurpesi** [comment]
Hey :)

I followed the steps all the way through and after i after i run node server.js the command window says "Plextogether server successfully started on port 8089"

When i try to access localhost:8089 i get the error

I´m probably doing something wrong here....

**Comment by samcm** [comment]
Yes they're two separate entities, you're running the server not the web app. Here are the instructions:

`git clone https://github.com/samcm/plextogether
cd plextogether
npm install
npm run build`
When complete, copy the contents of dist/ to the root of your web server.

**Comment by DomiStyle** [comment]
It has been a while since I last used node.js but wouldn't it be possible to serve the static files via the node.js web server that is currently being used anyway?

That would eliminate the need to run an extra web server just for a little bit of static content. It would also make using a reverse proxy easier.

**Comment by samcm** [comment]
Yup its entirely possible.

I'm actually planning on implementing an express server to run the web app anyway. It'll let us do stuff like link shortening for directly linking a room to someone. Should help out this issue.

**Comment by samcm** [comment]
This issue should be way less frequent past 1.01 with the web app and the server now being served up via Express. Closing for now.
