### ISSUE TITLE
Playing on multiple TV's

### ISSUE THREAD

**Issue by aporzio1** [samcm/PlexTogether#23]
If I understand correctly, you can only sync between 2 different accounts, is there a way to have 2 devices on the same account?

i.e. living room and bedroom TV so I can walk between the 2 rooms while watching the same thing

**Comment by samcm** [comment]
You can use the same Plex account as many times as you want within PT - it handles multiple instances from the same Plex user. 

The way to do what you want at the moment is to have multiple windows/tabs each connected to their own Plex Client. It's definitely not ideal but unfortunately including native support for one-to-many would require a near complete rewrite. The app simply wasn't built for this purpose i'm afraid.
