### ISSUE TITLE
When hosts stops or changes episodes. Same episodes restarts for others.

### ISSUE THREAD

**Issue by jsebtessier** [samcm/PlexTogether#29]
When the hosts stops playing (exit the what is currently playing) or changes to previous or next episode, the clients (other people than the host) in the plex together room simply restart the same episode instead of exiting/changing episode.

I tested this with Plex Media Player so far.

**Comment by samcm** [comment]
This is somewhat fixed in the dev branch; if the host quits what they're watching everyone else does as well. Its not perfect but there isn't a clear way to have the best of both worlds.

**Comment by jsebtessier** [comment]
How would I proceed to build the dev branch. Sorry im a noob, I have no idea how git and compiling works.

**Comment by samcm** [comment]
Easiest way would be to just access it through http://dev.plextogether.com - it's not an automatic build but I update it every couple of days.

**Comment by jsebtessier** [comment]
What server should I use while on this version?

**Comment by samcm** [comment]
US1, EU1 and AU1 should all be compatible at the moment

**Comment by samcm** [comment]
Fixed with v1.1
