### ISSUE TITLE
Not detecting what I'm watching, only the time watched.

### ISSUE THREAD

**Issue by MrTroot** [samcm/PlexTogether#30]
PMS Version 1.7.1.3856
PMP Version 7.7.0
Windows 10

When I start watching something, Plex Together loads up how far into the content I am but will not show what I'm watching. [http://i.imgur.com/NeJjfC0.png](http://i.imgur.com/NeJjfC0.png) (The screenshot is using OpenPHT, it is doing the same with PMP but I tried both to see if it was the client.)

**Comment by MrTroot** [comment]
Should have checked first, this is happening only on Chrome with Version 58.0.3029.110. FIrefox seems to work just fine.

**Comment by samcm** [comment]
This means that PlexTogether was unable to get a valid response out of the Plex Media Server. Are you running your Plex Media Server behind a reverse proxy or something like that? 

Weird that it works in Firefox though. I'm on that exact Chrome version right now and everything is working as intended.
