### ISSUE TITLE
Resume On Deck Items?

### ISSUE THREAD

**Issue by MrDevanWright** [samcm/PlexTogether#38]
As far as I can tell, when selecting an on deck item to play, the option to "Resume" or "Start From The Beginning" is not given when beginning the item.

**Comment by samcm** [comment]
Will add this for next release. Playing new content from an offset actually isn't implemented anywhere throughout the app (eg. autoplay). I'll fix that up as well.

**Comment by samcm** [comment]
Fixed with latest commit - you can now select a specific version of the content (note: not quality) and if you want to resume from where you are up to.
