### ISSUE TITLE
Home Options?

### ISSUE THREAD

**Issue by MrDevanWright** [samcm/PlexTogether#39]
Currently, the only way I can figure out how to go back to my library's home page is to go into the "Playback Settings" and clicking "Stop Playback." It would be appreciated to have a simpler button, possibly located just next to the "Playback Settings" that says "Home" or "Stop Playback." It's fine now because I figured it out, but for newer users it may take some time. Stopping playback and going back home wasn't something I initially thought would be a "Setting".

**Comment by gcordalis** [comment]
Adding clarity - a simpler way to return to library view while playing media

**Comment by samcm** [comment]
I think this should be clearer now. It's still a bit janky but should be ok.
