### ISSUE TITLE
Running as a Service

### ISSUE THREAD

**Issue by 14ngr15t** [samcm/PlexTogether#48]
Hi,

I'm trying to run PlexTogether as a windows service to run on boot (The web client, not server).  I am trying to configure the service using NSSM, but can't seem to get it working.  Attached is my settings in NSSM, but every time I try to start it, I get an error.  Any idea how to configure this correctly?

![capture](https://user-images.githubusercontent.com/11065277/28292873-119726cc-6b06-11e7-8dc9-dd4d0cd41600.JPG)

**Comment by samcm** [comment]
I'm not too familiar with NSSM unfortunately.  Does it run ok outside of NSSM? What error do you get when you run it with NSSM?

Ps. I think your arguments for url should be port 8089 instead of 8099 although this won't impact starting the server.
