### ISSUE TITLE
Error when trying to run.

### ISSUE THREAD

**Issue by Elrique64** [samcm/PlexTogether#5]
I sent **sam cm** a PM on the Plex forums about maybe testing this on my NAS.  (He should be able to figure who by reading the PM on those boards.)  I tried running this from a PuTTY window made from WinSCP on the NAS and get an error.  This is the command line I entered:

_exec nohup mono /volume1/misc//PlexTogether/server/server.js_

The error I get in nohub.out is:

**Cannot open assembly '/volume1/misc//PlexTogether/server/server.js': File does not contain a valid CIL image.**

I get the same error when I try this command from within PuTTY as well:  

_mono /volume1/misc//PlexTogether/server/server.js_

Don't know a lot about Mono, so this might be a bit beyond my abilities to fix without a tad bit of help.  :)

**Comment by pureMidi** [comment]
The server is built on node so the appropriate command to run is: node path/server.js

You'll need to make sure node is installed on your NAS before running this

**Comment by Elrique64** [comment]
NM, brain fart....  I got node and mono mixed up...  Sorry...
