### ISSUE TITLE
SyntaxError: Block-scoped declarations...

### ISSUE THREAD

**Issue by Brandon4466** [samcm/PlexTogether#6]
When attempting to run "sudo node server.js" I get the following error:

**Comment by Brandon4466** [comment]
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by Brandon4466** [comment]
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

**Comment by samcm** [comment]
Looks like you're on Node v4. Upgrade to Node v6 and you should be good :)

**Comment by samcm** [comment]
Closing this for now, let me know if an upgrade doesn't solve it.
