### ISSUE TITLE
Plex Together does not see Samsung Plex client

### ISSUE THREAD

**Issue by spotrh** [samcm/PlexTogether#62]
My Samsung Smart TV has a built in Plex client, but when I auth to PlexTogether, it does not show up in the client list.

**Comment by samcm** [comment]
If you're signed in to the same Plex account on both your TV and PlexTogether then this is unfortunately a Plex issue. We rely on the Plex API to tell us about clients, and other methods of discovering clients are out of the question as we are Web based. Sometimes it can take a while for clients to show up on your account - signing in and out may help. 

More info at #45
