### ISSUE TITLE
Autojoin/Disable server select on self-hosted setups

### ISSUE THREAD

**Issue by rix1337** [samcm/PlexTogether#63]
I would highly appreciate an option to disable the server selection.
Why would I run this tool on my own server, if it still shows the publicly avaible PT ones?

Please allow us to set a cookie, environment variable or anything else to skip the server selection and instead use the current instance.

**Comment by rix1337** [comment]
NVM, found out how to do this and created a script for my dockerfile

**Comment by samcm** [comment]
Glad you got a solution working. Can you post any more info on how you achieved that?

**Comment by rix1337** [comment]
https://github.com/rix1337/docker-plextogether-autojoin/blob/master/run.sh

**Comment by rix1337** [comment]
I need to test my solution further, but I modified the docker run script to check if $AUTOJOIN is set.

If so, it modifies two values in the store.js and rebuilds the app.
If my crude method of creating a placeholder file afterwards works, this will only rebuild once per docker pull.

I was frustrated because I couldn't set this up through nginx, but this method should be quite solid, if it works.

**Comment by rix1337** [comment]
See my solution@ https://github.com/rix1337/docker-plextogether-autojoin/blob/master/run.sh

I need to test my solution further, but I modified the docker run script to check if $AUTOJOIN is set. The commands worked locally, but my docker image is still building@https://hub.docker.com/r/rix1337/docker-plextogether-autojoin/builds/

```#!/bin/sh
cd /opt/plextogether
if [[ -v AUTOJOIN ]]; then
	if [ ! -f autojoinenabled ]; then
		sed -i -e "s/autoJoin: false/autoJoin: true/g" /opt/plextogether/src/store.js
		sed -i -e "s/autoJoinUrl: null/autoJoinUrl: '$DOMAIN'/g" /opt/plextogether/src/store.js
		npm run build
		touch autojoinenabled
	fi
fi
npm run server & node webapp.js --url=https://$DOMAIN/ptweb
```

If so, it modifies two values in the store.js and rebuilds the app.
If my crude method of creating a placeholder file afterwards works, this will only rebuild once per docker pull.

I was frustrated because I couldn't set this up through nginx, but this method should be quite solid, if it works.

**Comment by rix1337** [comment]
Confirmed working now.

**Comment by samcm** [comment]
Sweet, nice job and an interesting solution haha.

As you can probably see configuring stuff like this is a bit of a pain at the moment. Hopefully that will improve for v2, possibly in the form of an admin UI or something along those lines.

**Comment by rix1337** [comment]
Well to me this app already looks super polished.. and these few lines in bash are no "real" trouble.

I just opened this issue, because I did not look at the code close enough..
