### ISSUE TITLE
Issue connecting directly with the public IP

### ISSUE THREAD

**Issue by TheGrimmChester** [samcm/PlexTogether#7]
http://192.168.10.154:32433/player/timeline/poll?wait=0&commandID=46&type=video
Hitting server PC-M via https://PUBLIC_IP_HERE.2c88d71e818449a5a90e700206211a1f.plex.direct:29324
Raw response back from the PMS Server PC-M is below
Body VVV
undefined
Error VVV
{ Error: connect ECONNREFUSED 173.179.197.21:29324
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: 'PUBLIC_IP_HERE',
  port: 29324 }
Response back from metadata request
null
Didnt find a compatible PMS Metadata object because result == null. Result from the server is below
null

**Comment by samcm** [comment]
Confirmed https://github.com/samcm/PlexTogether/commit/df83c0c7da7b842685017941c479db748b336479 fixes this on two machines in different networks with identical setups. Let me know if it fixes it for you @TheGrimmChester
